name: protoc -test

on:
  push:
    branches: [ "main" ]

#设置操作系统
jobs:
  build:

    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v3
        
      - name: Install dependencies
        run: |
          pip install -r requirements.txt 
          python -m grpc_tools.protoc --proto_path=./protos  --python_out=./protos  --grpc_python_out=./protos ./protos/*.proto
        shell: cmd
          
      - name: python running
        run: python3 main.py        
        shell: cmd
       
      - name: pyinstaller
        run: pyinstaller main.py  -p ./protos
        shell: cmd
        
      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ${{ runner.os }} pyinstaller
          path: ./dist
          
