name: protoc -test

on:
  push:
    branches: [ "main" ]

#设置操作系统
jobs:
  build:

    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v3
        
      - name: Install dependencies
        run: |
          D:\anaconda3\envs\cinty\python.exe -m grpc_tools.protoc --proto_path=./protos  --python_out=./protos  --grpc_python_out=./protos ./protos/*.proto
          D:\anaconda3\envs\cinty\python.exe main.py  
          D:\anaconda3\envs\cinty\Scripts\pyinstaller.exe main.py  -p ${{ github.workspace }}/protos
        
      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ${{ runner.os }} pyinstaller
          path: ./dist
          
